export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const INIT_PURCHASED_PRODUCTS = "INIT_PURCHASED_PRODUCTS";
export const INIT_PRODUCTS = "INIT_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";
